### ISSUE TITLE
Bug report: "eager steiner fullycon" - staq hangs

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/staq#16]
Here is a test case [input.zip](https://github.com/softwareQinc/staq/files/4639410/input.zip)

Good:

`./staq   -S   -m   -O1   -d tokyo   -M steiner   -l eager   -f qasm   input.qasm`

Bad:

`./staq   -S   -m   -O1   -d fullycon   -M steiner   -l eager   -f qasm   input.qasm`

The bad one will hang.

**Comment by meamy** [comment]
Fixed. Thanks for the report!
