### ISSUE TITLE
Bug report: CX gate on the same qubit

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/staq#17]
Here is a test case [input.zip](https://github.com/softwareQinc/staq/files/4639420/input.zip)

`./staq   -S   -m   -O1   -d fullycon   -M swap   -l eager   -f qasm   input.qasm`

Something like this will appear in the output:

> CX q[0],q[0];

The OpenQASM spec is let loose on that syntax, but I think that should be deemed an outright syntax error.

**Comment by meamy** [comment]
Fixed. The issue was with "self-edges" from a qubit to itself in the fully connected map. Thanks for letting us know!
