### ISSUE TITLE
Output qubit mapping information

### ISSUE THREAD

**Issue by meamy** [softwareQinc/staq#20]
As per issue #18 the compiler should provide information about the mapping between qubits of the input circuit and the output, possibly in JSON format.

**Comment by DevelopDaily** [comment]
Awesome! Thank you.

On second thought, I am not sure if my earlier suggestion of the `JSON `format is proper. I mean, if the mapping relationship is simple enough, a simple text output file would suffice, as log as it can be parsed easily.

One of the beautiful things I appreciate very much about `staq `is that it is so useful yet its dependency on other libraries has been kept at a minimum.

`JSON `output is nice, but introducing a new dependency on a `JSON `library may be an overkill.

**Comment by meamy** [comment]
I've added information about the physical layout via comments in the openQASM output. I'll leave this open since there might need to be some tweaks depending on feedback. This seemed like the most sensible option to me rather than a separate file.

**Comment by DevelopDaily** [comment]
The original problem described in the issue #18 has been fixed. Thanks.

But, when I tried the procedure in the issue #18 by using `tokyo `instead of `square`, it does not produce the expected result. Could you please try that?

If you want me to elaborate on my `tokyo `result, I will post it.

**Comment by meamy** [comment]
It seems to me that the circuits are the same, accounting for the different mapping. This is what I get:

Square:
```output_square.qasm
// Mapped to device "9 qubit square lattice"
// Qubits: 9
// Layout (physical --> virtual):
// 	q[0] --> q[0]
// 	q[1] --> q[3]
// 	q[2] --> q[1]
// 	q[3] --> 
// 	q[4] --> q[2]
// 	q[5] --> 
// 	q[6] --> 
// 	q[7] --> 
// 	q[8] --> 

OPENQASM 2.0;
include "qelib1.inc";

qreg q[9];
U(0,0,0+0) q[1];
U(pi/2,0,pi) q[1];
U(pi/2,0,pi) q[4];
U(pi/2,0,pi) q[2];
U(pi/2,0,pi) q[0];
CX q[0],q[1];
CX q[1],q[0];
U(-0.339837,0,0) q[1];
CX q[1],q[2];
CX q[2],q[1];
CX q[0],q[1];
CX q[1],q[2];
U(0.785398,0,0) q[1];
CX q[2],q[1];
CX q[0],q[1];
U(-0.785398,0,0) q[1];
CX q[4],q[1];
CX q[2],q[1];
CX q[1],q[4];
CX q[4],q[1];
CX q[0],q[1];
U(-0.392699,0,0) q[1];
CX q[4],q[1];
U(0,0,0) q[1];
CX q[2],q[1];
U(-1.1781,0,0) q[1];
CX q[4],q[1];
CX q[0],q[1];
U(0.392699,0,0) q[1];
CX q[4],q[1];
CX q[2],q[1];
U(-0.392699,0,0) q[1];
CX q[4],q[1];
```

Tokyo:
```output_tokyo.qasm
// Mapped to device "20 qubit IBM Tokyo device"
// Qubits: 20
// Layout (physical --> virtual):
// 	q[0] --> q[0]
// 	q[1] --> q[3]
// 	q[2] --> q[1]
// 	q[3] --> 
// 	q[4] --> 
// 	q[5] --> 
// 	q[6] --> q[2]
// 	q[7] --> 
// 	q[8] --> 
// 	q[9] --> 
// 	q[10] --> 
// 	q[11] --> 
// 	q[12] --> 
// 	q[13] --> 
// 	q[14] --> 
// 	q[15] --> 
// 	q[16] --> 
// 	q[17] --> 
// 	q[18] --> 
// 	q[19] --> 

OPENQASM 2.0;
include "qelib1.inc";

qreg q[20];
U(0,0,0+0) q[1];
U(pi/2,0,pi) q[1];
U(pi/2,0,pi) q[6];
U(pi/2,0,pi) q[2];
U(pi/2,0,pi) q[0];
CX q[0],q[1];
CX q[1],q[0];
U(-0.339837,0,0) q[1];
CX q[1],q[2];
CX q[2],q[1];
CX q[0],q[1];
CX q[1],q[2];
U(0.785398,0,0) q[1];
CX q[2],q[1];
CX q[0],q[1];
U(-0.785398,0,0) q[1];
CX q[6],q[1];
CX q[2],q[1];
CX q[1],q[6];
CX q[6],q[1];
CX q[0],q[1];
U(-0.392699,0,0) q[1];
CX q[6],q[1];
U(0,0,0) q[1];
CX q[2],q[1];
U(-1.1781,0,0) q[1];
CX q[6],q[1];
CX q[0],q[1];
U(0.392699,0,0) q[1];
CX q[6],q[1];
CX q[2],q[1];
U(-0.392699,0,0) q[1];
CX q[6],q[1];
```

The outputs only differ in that ```q[4]``` in the square mapping is replaced by ```q[6]```, which both correspond to ```q[2]``` in the input circuit. Do you get the same output?

Thanks for taking the time to test this!

**Comment by DevelopDaily** [comment]
Shame on me. I made a stupid error in my spreadsheet that is used to tally and analyze the results.

You are correct. I am going to run all my test cases and keep you informed. 

Again, thank you for this amazing tool.

**Comment by meamy** [comment]
No worries at all! Glad to hear it appears to be correct. Let me know if you encounter any other issues.

**Comment by DevelopDaily** [comment]
I tested all the available devices `(tokyo|agave|aspen-4|singapore|square|fullycon)` to create two contrived states (equal probabilities and ascending probabilities). All perfect.

What I haven't done and plan to do is to find out how the QFT gates (up to 16 qubits) in my system will behave when they are mapped to the physical devices.

**Comment by DevelopDaily** [comment]
I use a customized `qelib1.inc` and the result does not seem to be correct. The `qelib1.inc` comes from the  [qpp project](https://github.com/softwareQinc/qpp/blob/master/include/qasm/preprocessor.h). The major differences are these:

The standard version of the `qelib1.inc` specified in the `OpenQASM`:

```
gate rx(theta) a { u3(theta,-pi/2,pi/2) a; }
gate ry(theta) a { u3(theta,0,0) a; }
```

The `qpp` version of the `qelib1.inc`:

```
gate r(theta, phi) a { u3(theta,phi-pi/2,-phi+pi/2) a; } 
gate rx(theta) a { r(theta,0) a; }  
gate ry(theta) a { r(theta,pi/2) a; } 
```

Then, I use a simple `input.qasm` like this:

```
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];

h q;
ry(-0.33983691) q[1];
```

Run this with the standard `qelib1.inc`, which is present in the current directory of the `input.qasm`.

`./staq -m -d square -f qasm -o output_standard.qasm input.qasm`

Run this with the customized `qelib1.inc`, whose `rx `and `ry `gates are replaced.

`./staq -m -d square -f qasm -o output_custom.qasm input.qasm`

The two output files are significantly different. I mean, they may look very similar, but they will produce drastically different final states.

The standard output:

```
// Mapped to device "9 qubit square lattice"
// Qubits: 9
// Layout (physical --> virtual):
// 	q[0] --> q[0]
// 	q[1] --> q[1]
// 	q[2] --> 
// 	q[3] --> 
// 	q[4] --> 
// 	q[5] --> 
// 	q[6] --> 
// 	q[7] --> 
// 	q[8] --> 

OPENQASM 2.0;
include "qelib1.inc";

qreg q[9];
U(pi/2,0,pi) q[0];
U(pi/2,0,pi) q[1];
U(-0.339837,0,0) q[1];

```
The custom output:

```
// Mapped to device "9 qubit square lattice"
// Qubits: 9
// Layout (physical --> virtual):
// 	q[0] --> q[0]
// 	q[1] --> q[1]
// 	q[2] --> 
// 	q[3] --> 
// 	q[4] --> 
// 	q[5] --> 
// 	q[6] --> 
// 	q[7] --> 
// 	q[8] --> 

OPENQASM 2.0;
include "qelib1.inc";

qreg q[9];
U(pi/2,0,pi) q[0];
U(pi/2,0,pi) q[1];
U(-0.339837,(pi/2)-(pi/2),-((pi/2)+(pi/2))) q[1];

```
The results do not necessarily mean the `staq `is wrong. If you can give the `staq `a clean bill of health, I will move on to the `qpp `project to file an issue.

Thanks.

**Comment by meamy** [comment]
Hmm, this one is a bit difficult. Neither result is incorrect as far as I can tell --- they both expand the gates correctly given the version of the standard library. In the ```qpp``` case, the final gate differs by Rz(pi), which seems consistent with the discussion from the ```qpp``` project where it was found that the standard library implements ```H``` up to phase.

So, the question now is what to do. What I'm thinking is to provide an alternate ```qelib``` in the repository for compatibility with ```qpp```. That way programmers can choose which version, e.g., either by importing ```qelib1.inc``` or ```qelibqpp.inc```

**Comment by DevelopDaily** [comment]
When I run the standard `staq` output with the `qpp `testing tool `qasm2` like this;

`./qasm2 output_standard.qasm "2 3 4 5 6 7 8"`

I get this:

```
>> Final state:
0.57735   0.408248   0.57735   0.408248 
```

Run the customized `staq `output

`./qasm2 output_custom.qasm "2 3 4 5 6 7 8"`

I get this:

```
>> Final state:
0.408248   -0.57735   0.408248   -0.57735 

```
So, from the point of view of `qpp`, the final state of the `output_custom.qasm` is wrong. If the `ry(pi) q[1]; `is added to the end of the `output_custom.qasm`, its final state will match that of the `output_standard.qasm`.

**Comment by DevelopDaily** [comment]
Since the final states actually differ by `ry(pi)`, I scrutinize more of the `ry `definition in the `qpp `customized `qelib1.inc`. The gate `ry `is backed up by the gate `r`. I speculate there may be a parse error in the `staq `or one of its dependencies. Here is a test.

If the `qelib1.inc` has this line:

`gate r(theta, phi) a { u3(theta,phi-pi/2,-phi+pi/2) a; }`

The staq outputs this line:

`U(-0.339837,(pi/2)-(pi/2),-((pi/2)+(pi/2))) q[1];`

If the `qelib1.inc` has this line:

`gate r(theta, phi) a { u3(theta,phi-pi/2,pi/2-phi) a; }`

The staq outputs this line:

`U(-0.339837,(pi/2)-(pi/2),(pi/2)-(pi/2)) q[1];`

The difference between` -phi+pi/2` and `pi/2-phi` in the `qelib1.inc` should not trigger any different outcomes of the `staq`. The expressions `-phi+pi/2` and `pi/2-phi` are equivalent in that context, aren't they?

**Comment by meamy** [comment]
Good catch, I hadn't noticed that. They are equivalent in the context. The parser didn't have the correct precendence for the unary - operator in this case, so it was being associated incorrectly. This is fixed now.

Thanks!

**Comment by DevelopDaily** [comment]
Here is a test case to reveal another bug.

```
// linear.qasm
OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];

h q;
swap q[2], q[0];
cx q[0], q[2];
ry(-0.33983691) q[2];

```

Run this:

`./staq   -S   -m   -O1   -d   square   -M   swap   -l   linear   -f   qasm   -o   output_linear.qasm   linear.qasm
`

The result in the `output_linear.qasm` looks like this:

```
// Mapped to device "9 qubit square lattice"
// Qubits: 9
// Layout (physical --> virtual):
// 	q[0] --> q[0]
// 	q[1] --> q[1]
// 	q[2] --> q[2]
// 	q[3] --> 
// 	q[4] --> 
// 	q[5] --> 
// 	q[6] --> 
// 	q[7] --> 
// 	q[8] --> 

OPENQASM 2.0;
include "qelib1.inc";

qreg q[9];
U(pi/2,0,pi) q[0];
U(pi/2,0,pi) q[1];
U(pi/2,0,pi) q[2];
CX q[2],q[1];
CX q[1],q[2];
CX q[2],q[1];
CX q[1],q[0];
CX q[0],q[1];
CX q[1],q[0];
CX q[0],q[1];
U(-0.339837,(pi/2)-(pi/2),(pi/2)-(pi/2)) q[1];

```
Note that the 3 qubits have a straight 1 to 1 mapping relationship, thus one expects the `linear.qasm` and `output_linear.qasm` would produce the same final state. In reality, they don't.

The final state of the `linear.qasm`:

```
>> Final state:
0.408248   0.288675   0.408248   0.288675   0.408248   0.288675   0.408248   0.288675
```

The final state of the `output_linear.qasm` (after discarding the unused qubits 3-8):

```
>> Final state:
0.408248   0.408248   0.288675   0.288675   0.408248   0.408248   0.288675   0.288675

```

**Comment by meamy** [comment]
Right, with the ```swap``` mapper the layout at the end of the circuit is not necessarily the same as the mapping at the beginning. I had overlooked that when outputting the layout since the ```steiner``` algorithm operates differently.

Thanks for bringing this to our attention! I'll try to fix this ASAP, but I'll have to rethink a few of the details of the implementation first.

As an aside, that's not a great circuit it synthesizes for this case. I'd like to improve that if possible at the same time.

**Comment by meamy** [comment]
The latest commit should fix this. For the command ```./staq -S -m -O1 -d square -M swap -l linear -f qasm -o output_linear.qasm linear.qasm``` the compiler now outputs the following:

```qasm
// Mapped to device "9 qubit square lattice"
// Qubits: 9
// Input layout (physical --> virtual):
// 	q[0] --> q[0]
// 	q[1] --> q[1]
// 	q[2] --> q[2]
// 	q[3] --> 
// 	q[4] --> 
// 	q[5] --> 
// 	q[6] --> 
// 	q[7] --> 
// 	q[8] --> 
// Output layout (physical --> virtual):
// 	q[0] --> q[0]
// 	q[1] --> q[2]
// 	q[2] --> q[1]
// 	q[3] --> 
// 	q[4] --> 
// 	q[5] --> 
// 	q[6] --> 
// 	q[7] --> 
// 	q[8] --> 

OPENQASM 2.0;
include "qelib1.inc";

qreg q[9];
U(pi/2,0,pi) q[0];
U(pi/2,0,pi) q[1];
U(pi/2,0,pi) q[2];
CX q[2],q[1];
CX q[1],q[2];
CX q[2],q[1];
CX q[1],q[0];
CX q[0],q[1];
CX q[1],q[0];
CX q[0],q[1];
U(-0.339837,0,0) q[1];
```

The final layout gives the output amplitudes, as given in the previous comment. It's a bit confusing because the original circuit actually performs a swap, so the swap on ```q[0]``` doesn't show in the output mapping which only reports which virtual qubit a physical qubit is assigned to at the end of the circuit.

All of this is to say, the ```steiner``` mapper is really the way to go (IMHO). No multiple levels of indirection to juggle and better ```CX``` counts.

**Comment by DevelopDaily** [comment]
Great. Thanks.

Now, I can run some non-trivial circuits, and will let you know the results.
