### ISSUE TITLE
Failed to parse floating-point numbers in scientific notation form (OpenQASM)

### ISSUE THREAD

**Issue by tnguyen-ornl** [softwareQinc/staq#24]
When using staq to compile the QFT QASM source from [here](https://github.com/Qiskit/openqasm/blob/master/benchmarks/qft/qft_n20.qasm), it failed to parse floating-point numbers in scientific notation form (e.g. line 474.)
```
qft.qasm:474:20: expected RPAREN but got ID
qft.qasm:476:21: expected RPAREN but got ID
qft.qasm:478:20: expected RPAREN but got ID
qft.qasm:545:20: expected RPAREN but got ID
```

**Comment by meamy** [comment]
Fixed.
