### ISSUE TITLE
Question on Evaluating Staq

### ISSUE THREAD

**Issue by khieta** [softwareQinc/staq#46]
Hi, I'm working on an updated version of [our paper](https://arxiv.org/pdf/1912.02250.pdf) on verified optimization of quantum circuits and I'd like to include Staq's results on our benchmarks. What is the best way to evaluate Staq's optimizations (without routing)? I'd like to use the Python interface if possible. I was thinking that I should emulate Staq's `-O3` option, which does `simplify`, `rotfold` and `cnotsynth` (per [staq/main.cpp#L217](https://github.com/softwareQinc/staq/blob/main/staq/main.cpp#L217)), but I don't see a Python binding for the `cnotsynth` pass. Is there a reason for this?

Additionally, if I wanted to evaluate both optimization and routing, which of Staq's optimizations will preserve connectivity guarantees? (And do you expect the optimizations would have any effect on routed circuits?)

Thanks!

**Comment by vsoftco** [comment]
adding @meamy

**Comment by vsoftco** [comment]
@khieta thanks, we'll take a look and get back to you

**Comment by khieta** [comment]
Thanks for the help!

**Comment by ashsaki** [comment]
@meamy I used `-O3` before the `swap` router, but it did not preserve the connectivity, i.e., there were no SWAPs. Any idea?

My full command:
```
staq -S -O3 -m --device device.json -l bestfit -M swap -f qasm <input 10-qubit qasm file>
```
