### ISSUE TITLE
Crashes: staq -S  -m  -d square  -M steiner  add_3_5.qasm

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/staq#5]
When the `staq` is run with these arguments `-S  -m  -d square  -M steiner  add_3_5.qasm`, it crashes.

So, I change the code to try to catch `std::exception`, and its `what()` is printed out and it looks like this:

`No indices left to pivot on, but multiple vectors remain! `

**Comment by vsoftco** [comment]
@meamy Matt, any idea?

**Comment by meamy** [comment]
Thanks for pointing this out! The exception is misleading in this case -- the `square` device is currently a fixed 3x3 square lattice, so the  `add_3_5.qasm` circuit doesn't fit. It looks like the error is recognized, but no exception is raised so it gets called further down the line. I'll see what the best solution is.

**Comment by meamy** [comment]
Fixed now.
