### ISSUE TITLE
Weird: staq hangs when it runs this qasm file.

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/staq#9]
I will characterize the problem as this:

If the last line of a QASM file is a comment line that is not followed by a new line/line feed, the staq will hang. See the attached file [weird.zip](https://github.com/softwareQinc/staq/files/4335621/weird.zip), which looks like this:

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> //
> 
Now, run this and it will never end.

`./staq weird.qasm`

**Comment by meamy** [comment]
Thanks for pointing this out. It looks to be a bug in the parser. I can't test it at the moment, but I'll push a fix in the next day or two.

**Comment by meamy** [comment]
Fixed, closing this now.
